version: '3'
services:
  php:
    image: thecodingmachine/php:7.2-v2-cli
    tty: true
    command: bash
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - PHP_EXTENSION_INTL=1
      - PHP_EXTENSION_PDO_SQLITE=1
      - STARTUP_COMMAND_1=composer install
